name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy main branch to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: hera.krystal.co.uk
          port: 722
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            cd sneakersouq
            git pull
            composer install --optimize-autoloader --no-dev
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate
            source /home/firestor/nodevenv/sneakersouq/16/bin/activate && cd /home/firestor/sneakersouq
            npm run build
            deactivate

